# Generated by Django 6.0.2 on 2026-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_priority_and_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_datetime',
            field=models.DateTimeField(blank=True, help_text='Deadline date and time', null=True),
        ),
    ]
