# Generated by Django 6.0.2 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_due_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Time allocated in minutes', null=True),
        ),
    ]
